### ISSUE TITLE
气泡图配色问题

### ISSUE THREAD

**Issue by sayhello854123** [junjunlab/jjAnno#1]
老俊俊我也不写英文了，你给的data("pdot")数据，我参考了你的源码，想要了解如何改变球的颜色例如添加成‘viridis’
![image](https://user-images.githubusercontent.com/53084301/179875674-6dd71832-0bb4-4a3e-817a-f868aa852048.png)

**Comment by junjunlab** [comment]
你是指最开始画图的时候?好像这个问题和jjAnno无关,建议你去群里进行提问哦

**Comment by junjunlab** [comment]
non-relavent
